# Generated by Django 5.2.5 on 2025-11-25 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cuenta'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='appliances_data',
            field=models.JSONField(blank=True, default=list, verbose_name='Datos de Artefactos'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='calibration_serial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serie Patrón'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='checklist_items',
            field=models.JSONField(blank=True, default=dict, verbose_name='Items de Verificación'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='client_email_form',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Cliente Formulario'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Cliente'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='client_signature',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Digital Cliente'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='co_detector_brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca Detector CO'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='co_detector_model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo Detector CO'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='co_detector_serial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serie Detector CO'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='critical_defects',
            field=models.JSONField(blank=True, default=list, verbose_name='Defectos Críticos'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='current_step',
            field=models.IntegerField(default=1, verbose_name='Paso Actual del Formulario'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='form_completed_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje Completado'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='has_calibration_pattern',
            field=models.BooleanField(default=False, verbose_name='Patrón de Rx'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='has_critical_defect',
            field=models.BooleanField(default=False, verbose_name='Defecto Crítico'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='has_internal_void',
            field=models.BooleanField(default=False, verbose_name='Cuenta con Vacío Interno'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='has_no_defects',
            field=models.BooleanField(default=False, verbose_name='Sin Defectos'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='has_non_critical_defect',
            field=models.BooleanField(default=False, verbose_name='Defecto No Crítico'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='has_property_certificate',
            field=models.BooleanField(default=False, verbose_name='Certificado de Tradición y Libertad'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Final'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_org_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Org'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_org_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Org'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_org_name',
            field=models.CharField(default='RUIS - Redes Urbanas Inspecciones S.A.S.', max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_org_nit',
            field=models.CharField(default='901 563 111-9', max_length=50, verbose_name='NIT'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_type_follow_up',
            field=models.BooleanField(default=False, verbose_name='Seguimiento'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_type_modification',
            field=models.BooleanField(default=False, verbose_name='Modificación y Reforma'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_type_periodic',
            field=models.BooleanField(default=False, verbose_name='Revisión Periódica (10 años)'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_type_user_request',
            field=models.BooleanField(default=False, verbose_name='Solicitud del Usuario'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_affirms_safe',
            field=models.BooleanField(default=True, verbose_name='Inspector Afirma Condiciones Seguras'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_competence_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cédula Competencia Laboral'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Inspector'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_signature',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Digital Inspector'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_specialty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='installation_continues_service',
            field=models.BooleanField(default=True, verbose_name='Instalación Continúa en Servicio'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='last_revision_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Última Revisión'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='leak_test_appliances',
            field=models.BooleanField(default=False, verbose_name='Test en Artefactos'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='leak_test_meter',
            field=models.BooleanField(default=False, verbose_name='Test en Medidor'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='leak_test_method',
            field=models.CharField(blank=True, choices=[('DETECTOR', 'Detector'), ('ESPUMA', 'Espuma/Agua Jabón')], max_length=20, null=True, verbose_name='Método Prueba Hermeticidad'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='leak_test_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Presión de Prueba (mbar)'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='manometer_brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca Manómetro'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='manometer_model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo Manómetro'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='manometer_serial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serie Manómetro'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='meter_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Medidor'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='meter_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lectura Medidor (m³)'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='non_critical_defects',
            field=models.JSONField(blank=True, default=list, verbose_name='Defectos No Críticos'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='pressure_type',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='BAJA', max_length=10, verbose_name='Tipo de Presión'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='property_aspect',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aspecto Inmueble'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='rooms_data',
            field=models.JSONField(blank=True, default=list, verbose_name='Datos de Recintos'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='seal_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Sello'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='service_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Puesta en Servicio'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='supply_situation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Situación de Suministro'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='user_request_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Solicitud Usuario'),
        ),
    ]
