# Generated by Django 5.2.5 on 2025-11-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_alter_inspection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
