# Generated by Django 5.2.5 on 2025-11-21 08:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('GENERATING', 'Generando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/pdfs/', verbose_name='Archivo PDF')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('report_number', models.CharField(max_length=50, unique=True, verbose_name='Número de reporte')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del reporte')),
                ('include_photos', models.BooleanField(default=True, verbose_name='Incluir fotos')),
                ('include_signature', models.BooleanField(default=True, verbose_name='Incluir firma')),
                ('watermark', models.BooleanField(default=False, verbose_name='Marca de agua')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='inspections.inspection', verbose_name='Inspección')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inspection', 'created_at'], name='reports_rep_inspect_7e9a4f_idx'), models.Index(fields=['status'], name='reports_rep_status_c732ef_idx')],
            },
        ),
    ]
