# Generated by Django 5.2.5 on 2025-11-21 08:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('template_type', models.CharField(choices=[('WELCOME', 'Bienvenida'), ('VERIFICATION', 'Verificación de cuenta'), ('PASSWORD_RESET', 'Recuperación de contraseña'), ('INSPECTION_SCHEDULED', 'Inspección programada'), ('INSPECTION_REMINDER', 'Recordatorio de inspección'), ('INSPECTION_COMPLETED', 'Inspección completada'), ('INSPECTION_APPROVED', 'Inspección aprobada'), ('INSPECTION_REJECTED', 'Inspección rechazada'), ('REPORT_READY', 'Reporte disponible')], max_length=50, unique=True, verbose_name='Tipo')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('html_content', models.TextField(verbose_name='Contenido HTML')),
                ('text_content', models.TextField(blank=True, verbose_name='Contenido texto plano')),
                ('variables', models.JSONField(default=list, help_text='Lista de variables disponibles: {{ user_name }}, {{ inspection_date }}, etc.', verbose_name='Variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Plantilla de Email',
                'verbose_name_plural': 'Plantillas de Email',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('IN_APP', 'In-App')], default='IN_APP', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('FAILED', 'Fallido'), ('READ', 'Leído')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('email_to', models.EmailField(blank=True, max_length=254, verbose_name='Email destinatario')),
                ('email_subject', models.CharField(blank=True, max_length=200, verbose_name='Asunto email')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado en')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leído en')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inspections.inspection', verbose_name='Inspección')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='notificatio_user_id_cd4f27_idx'), models.Index(fields=['notification_type', 'status'], name='notificatio_notific_a659f1_idx'), models.Index(fields=['inspection'], name='notificatio_inspect_2c7b53_idx')],
            },
        ),
    ]
