# Generated by Django 5.2.5 on 2025-11-21 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Teléfono del Cliente')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Cliente')),
                ('client_dni', models.CharField(blank=True, max_length=15, null=True, verbose_name='DNI del Cliente')),
                ('address', models.CharField(max_length=300, verbose_name='Dirección')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio')),
                ('city', models.CharField(default='Montería', max_length=100, verbose_name='Ciudad')),
                ('scheduled_date', models.DateField(verbose_name='Fecha Programada')),
                ('scheduled_time', models.TimeField(verbose_name='Hora Programada')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada'), ('RESCHEDULED', 'Reagendada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Razón de Cancelación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('inspection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='inspections.inspection', verbose_name='Inspección Realizada')),
                ('inspector', models.ForeignKey(limit_choices_to={'role': 'INSPECTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_as_inspector', to=settings.AUTH_USER_MODEL, verbose_name='Inspector Asignado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registrado')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-scheduled_date', '-scheduled_time'],
                'indexes': [models.Index(fields=['scheduled_date', 'scheduled_time'], name='appointment_schedul_59e8bc_idx'), models.Index(fields=['status'], name='appointment_status_8fe9d7_idx'), models.Index(fields=['inspector'], name='appointment_inspect_573189_idx')],
            },
        ),
    ]
