# Generated by Django 5.2.5 on 2025-12-26 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_actual_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada'), ('RESCHEDULED', 'Reagendada'), ('NEEDS_RESCHEDULE', 'Requiere Reprogramación')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='CallTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Teléfono del Cliente')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Cliente')),
                ('client_dni', models.CharField(blank=True, max_length=15, null=True, verbose_name='DNI del Cliente')),
                ('client_address', models.CharField(max_length=300, verbose_name='Dirección')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='Última Inspección')),
                ('next_inspection_due', models.DateField(blank=True, null=True, verbose_name='Próxima Inspección')),
                ('days_until_due', models.IntegerField(default=0, verbose_name='Días para Vencimiento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completada'), ('APPOINTMENT_SCHEDULED', 'Cita Agendada'), ('CLIENT_REFUSED', 'Cliente Rechazó'), ('NO_ANSWER', 'No Contestó')], default='PENDING', max_length=30, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=20, verbose_name='Prioridad')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('call_attempts', models.PositiveIntegerField(default=0, verbose_name='Intentos de Llamada')),
                ('last_call_date', models.DateTimeField(blank=True, null=True, verbose_name='Última Llamada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='Asignado Por')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'CALL_CENTER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Asignado A')),
                ('client_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_tasks_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Cliente')),
                ('resulting_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_task', to='appointments.appointment', verbose_name='Cita Resultante')),
            ],
            options={
                'verbose_name': 'Tarea de Llamada',
                'verbose_name_plural': 'Tareas de Llamada',
                'ordering': ['priority', 'days_until_due', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='appointment_status_36f762_idx'), models.Index(fields=['assigned_to'], name='appointment_assigne_4e8d45_idx'), models.Index(fields=['priority'], name='appointment_priorit_5b20fc_idx'), models.Index(fields=['next_inspection_due'], name='appointment_next_in_2b870a_idx')],
            },
        ),
    ]
