# Generated by Django 5.2.5 on 2025-12-26 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_status_calltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltask',
            name='source_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_tasks', to='appointments.appointment', verbose_name='Cita a Reprogramar'),
        ),
        migrations.AddField(
            model_name='calltask',
            name='task_type',
            field=models.CharField(choices=[('INSPECTION_CALL', 'Llamada de Inspección'), ('RESCHEDULE', 'Reprogramación')], default='INSPECTION_CALL', max_length=20, verbose_name='Tipo de Tarea'),
        ),
    ]
