# Generated by Django 5.2.5 on 2025-11-21 08:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache_type', models.CharField(choices=[('ADMIN_STATS', 'Admin Statistics'), ('INSPECTOR_STATS', 'Inspector Statistics'), ('USER_STATS', 'User Statistics')], max_length=50, verbose_name='Tipo de cache')),
                ('data', models.JSONField(default=dict, verbose_name='Datos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('expires_at', models.DateTimeField(verbose_name='Expira en')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_caches', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cache de Dashboard',
                'verbose_name_plural': 'Caches de Dashboard',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'cache_type', 'expires_at'], name='dashboard_d_user_id_36ee36_idx')],
            },
        ),
    ]
