# Generated by Django 5.2.5 on 2025-11-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_inspection_date',
            field=models.DateField(blank=True, help_text='Fecha de la última inspección de gas realizada', null=True, verbose_name='Fecha de Última Inspección'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CALL_CENTER', 'Call Center'), ('INSPECTOR', 'Inspector'), ('USER', 'Usuario/Cliente')], default='USER', max_length=20, verbose_name='Rol'),
        ),
    ]
