# Generated by Django 5.2.5 on 2025-12-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_last_inspection_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='next_inspection_due',
            field=models.DateField(blank=True, help_text='Fecha en que vence la próxima inspección obligatoria', null=True, verbose_name='Próxima Inspección'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CALL_CENTER_ADMIN', 'Call Center Administrador'), ('CALL_CENTER', 'Call Center'), ('INSPECTOR', 'Inspector'), ('USER', 'Usuario/Cliente')], default='USER', max_length=20, verbose_name='Rol'),
        ),
    ]
